### ISSUE TITLE
Refactor to make your code more legible

### ISSUE THREAD

**Issue by arrested-developer** [FACxBeamery/joao-project-week-6#10]
https://github.com/FACxBeamery/joao-project-week-6/blob/5de69183c825a9fbf1a11250286551c5924e3619/src/utils/getQuestions.js#L5-L9

This code does exactly what you wanted it to do, which is great. However, you need to consider how easy it will be for others (or your future self) to read and understand your code. Refactor this module and try to make it as human readable as you possibly can

A couple of personal tips/opinions from me:

- Ternary operators can be extremely useful, but they can also be difficult to read. In this case I personally found the ternary operator along with template literals to be hard to read. 
- I would also question whether a ternary operator was appropriate when the third operand is an empty string
-  Assigning logic tests to well named variables can help make `if` statements or ternary operators more legible. This also allows you to use a positive test in your `if` statement (rather than a !==), e.g:

```javascript
const noCategorySelected = triviaCategory !== "any"
if (noCategorySelected) {
  // do the thing
}

**Comment by Joaoviana** [comment]
Thank you for the really clear explanation! I did find it somewhat cumbersome too.
