### ISSUE TITLE
unescape() is deprecated since Javascript version 1.5

### ISSUE THREAD

**Issue by arrested-developer** [FACxBeamery/joao-project-week-6#11]
https://github.com/FACxBeamery/joao-project-week-6/blob/5de69183c825a9fbf1a11250286551c5924e3619/src/components/Trivia.js#L19

It is not good practice to use deprecated functions. Javascript is very backward compatible and so will still support old code features. This function has been deprecated since version 1.5, which is a pretty long time ago! This might be because it can introduce security issues.

https://www.w3schools.com/jsref/jsref_unescape.asp

**Comment by Joaoviana** [comment]
DecodeURIcomponent is the alternative! thank you for pointing that out 😄 

https://github.com/FACxBeamery/joao-project-week-6/commit/43ccaa773a3c42b0867515fa31e8dfb3e273143d
