### ISSUE TITLE
Making an API call for every question is expensive for your client and server resources

### ISSUE THREAD

**Issue by arrested-developer** [FACxBeamery/joao-project-week-6#12]
https://github.com/FACxBeamery/joao-project-week-6/blob/5de69183c825a9fbf1a11250286551c5924e3619/src/components/Trivia.js#L32

You make a new API call every time a new question is needed, however each API call returns a result with multiple questions. Would it be possible to limit the API calls to make one only when new questions are needed?

**Comment by Joaoviana** [comment]
ooooh, i see, will check that now
